package POJOS;
// Generated 22-feb-2022 13:04:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private Integer idEmpresa;
     private String nombre;
     private String cif;
     private Set trabajadorbbdds = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(String nombre, String cif) {
        this.nombre = nombre;
        this.cif = cif;
    }
    public Empresas(String nombre, String cif, Set trabajadorbbdds) {
       this.nombre = nombre;
       this.cif = cif;
       this.trabajadorbbdds = trabajadorbbdds;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public Set getTrabajadorbbdds() {
        return this.trabajadorbbdds;
    }
    
    public void setTrabajadorbbdds(Set trabajadorbbdds) {
        this.trabajadorbbdds = trabajadorbbdds;
    }




}


